# Generated by Django 4.2.23 on 2026-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutlocation',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
