# Generated by Django 5.2.13 on 2026-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_productcategory_delete_navproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="gallery_image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_gallery/"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="gallery_image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_gallery/"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="specifications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
