# Generated by Django 5.2.13 on 2026-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_servicecategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicecategory",
            old_name="description",
            new_name="overview",
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="gallery_image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="service_gallery/"
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="gallery_image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="service_gallery/"
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="specifications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
