# Generated by Django 5.2.13 on 2026-06-03 05:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_service_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="applications",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="benefits",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="overview",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="specifications",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
