# Generated by Django 5.2.13 on 2026-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_servicecategory_applications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="seo_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
