# Generated by Django 5.2.13 on 2026-06-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_aboutlocation_map_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutlocation",
            name="map_embed_url",
        ),
        migrations.AddField(
            model_name="aboutlocation",
            name="map_image",
            field=models.ImageField(blank=True, null=True, upload_to="locations/"),
        ),
    ]
