# Generated by Django 5.2.13 on 2026-06-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_remove_aboutlocation_map_embed_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutlocation",
            name="map_image",
        ),
        migrations.AddField(
            model_name="aboutlocation",
            name="map_embed_url",
            field=models.URLField(
                blank=True, help_text="Google Maps Embed URL", null=True
            ),
        ),
    ]
