# Generated by Django 5.2.13 on 2026-06-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_aboutlocation_map_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutlocation",
            name="map_embed_url",
        ),
        migrations.AddField(
            model_name="aboutlocation",
            name="map_embed_code",
            field=models.TextField(
                blank=True,
                help_text="Paste complete Google Maps iframe code",
                null=True,
            ),
        ),
    ]
